from dotenv import load_dotenv
import os

from langchain_openai.chat_models import ChatOpenAI
from langchain_core.messages import AIMessage, HumanMessage


# =====================================================
# AI Messages
# =====================================================

# In the previous lesson we introduced HumanMessage and SystemMessage.
#
# In this lesson we'll look at another message type:
#
# AIMessage
#
# AIMessage represents a response generated by the language model.
#
# Besides storing previous chatbot responses, AI messages are commonly
# used for few-shot prompting, where we provide example conversations
# that teach the model how we would like it to respond.


# =====================================================
# Load the API Key
# =====================================================

# Load the environment variables from the .env file.

load_dotenv()

# Retrieve the OpenAI API key.

api_key = os.getenv("OPENAI_API_KEY")


# =====================================================
# Initialize the Chat Model
# =====================================================

chat = ChatOpenAI(
    model="gpt-5-mini",
    temperature=0,
    model_kwargs={"seed": 365}
)


# =====================================================
# Create Example Human Messages
# =====================================================

# HumanMessage objects represent user prompts.

message_human_dog = HumanMessage(
    content="I've recently adopted a dog. Could you suggest some dog names?"
)

message_human_cat = HumanMessage(
    content="I've recently adopted a cat. Could you suggest some cat names?"
)

message_human_fish = HumanMessage(
    content="I've recently adopted a fish. Could you suggest some fish names?"
)


# =====================================================
# Create Example AI Messages
# =====================================================

# AIMessage objects represent responses from the language model.
#
# Here we create example responses that demonstrate the sarcastic style
# we want the model to imitate.

message_ai_dog = AIMessage(
    content="Oh, absolutely. Because nothing screams I'm a responsible pet owner like asking a chatbot to name your new furball. How about 'Bark Twain'?"
)

message_ai_cat = AIMessage(
    content="Oh, absolutely. Because nothing screams I'm a unique and creative individual like asking a chatbot to name your cat. How about 'Furry McFurFace', 'Sir Meowsalot', or 'Catastrophe'?"
)


# =====================================================
# Few-Shot Prompting
# =====================================================

# Few-shot prompting teaches the model by showing it examples rather
# than simply giving it instructions.
#
# Here we provide:
#
# Human -> AI
# Human -> AI
#
# The model then receives a new HumanMessage and attempts to continue
# the conversation in the same style.

response = chat.invoke([
    message_human_dog,
    message_ai_dog,
    message_human_cat,
    message_ai_cat,
    message_human_fish
])


# =====================================================
# Display the Response
# =====================================================

# invoke() returns an AIMessage object.
#
# The generated text is stored in the content attribute.

print(response.content)


# =====================================================
# Notes
# =====================================================

# Few-shot prompting is a technique where we provide the model with
# example inputs and outputs before asking it a new question.
#
# Instead of explicitly describing how the model should respond, we
# demonstrate the desired behavior through examples.
#
# The more high-quality examples we provide, the easier it is for the
# model to recognize the desired response pattern.
#
# However, each additional example increases the number of prompt
# tokens, which also increases API cost.
#
# In practice, the best results are usually achieved by combining:
#
# - A SystemMessage that describes the chatbot's behavior.
# - Several HumanMessage / AIMessage example pairs.
# - A new HumanMessage containing the user's actual request.